name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Build the project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
